### PR TITLE
[Fix] improve liqoctl uninstall error message

### LINKED ISSUE #2821: Issue on liqo uninstallation
Hello everyone.

I have a central kubernetes cluster implemented on OpenStack with 3 machines (1 server and 2 agents) with k3s installed on it using:
`curl -sfL https://get.k3s.io | sh -s - server --disable traefik --node-external-ip <PUBLIC_IP_ADDRESS>`

and an edge node which is a minipc with k3s installed using:
`sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -s - --write-kubeconfig-mode 644-`

This is the installed version of liqo on both sides:
Screenshot from 2024-11-21 11-58-50

I was trying to establish liqo peering on the edge node (minipc) using this command:
`liqoctl peer --in-band --remote-kubeconfig <KUBECONFIG_FILE> --server-service-type NodePort`
 but it stuck at this stage:
Waiting for Connection status to be established

Then I tried to uninstall liqo using `liqoctl uninstall --purge` but it returned me this message:
 ERRO  Pre-uninstall checks failed: you should:                                                                                                           
       disable networking for clusters:
       - snowy-water

I need to remove all the clusterroles, clusterrolebindings, customresourcedefinition, services, deployments, daemonsets, pods, cronjob.batch, namespaces, mutatingwebhookconfigurations and validatingwebhookconfiguration related to liqo to be able to uninstall liqo itself.

### PR DESCRIPTION
**Pull request by claudiolor**
# Description

this patch improves the liqoctl uninstall error message when the pre-uninstall checks fail, by suggesting the user which command has to be used to unpeer a cluster.

Closes #2821

### CODE REVIEW

File: pkg/liqoctl/uninstall/handler.go [hunk 1]
```diff
@@ -66,7 +66,10 @@ func (o *Options) Run(ctx context.Context) error {
 
 	s := o.Printer.StartSpinner("Running pre-uninstall checks")
 	if err := utils.PreUninstall(ctx, o.CRClient); err != nil {
-		s.Fail("Pre-uninstall checks failed: ", output.PrettyErr(err))
+		errMsg := fmt.Sprintf("Pre-uninstall checks failed: %s\n"+
```
Comment (aleoli) [inline pkg/liqoctl/uninstall/handler.go:69]: Are we checking here also for offloaded namespaces? if so, I would add the command to unoffload namespaces too

**Review by aleoli — APPROVED** [review]

File: pkg/liqoctl/uninstall/handler.go [hunk 2]
```diff
@@ -66,7 +66,10 @@ func (o *Options) Run(ctx context.Context) error {
...
+			"You can disable the active peerings with other clusters with the 'liqoctl unpeer' command.\n"+
```
Comment (frisso) [inline pkg/liqoctl/uninstall/handler.go:70]: I would say "You must tear down the active peerings..." instead of "You can disable the active peering...."
Saying "you can", it means (to me) that it's just a suggestion, not a mandatory requirement to proceed.

Comment (claudiolor) [reply pkg/liqoctl/uninstall/handler.go:70]: The issue here is that the errors might not be related to the active peerings, but as @aleoli said, there might be also the possibility that there still is an offloaded namespace or other resources to remove. So I wouldn't always print to "You must tear down the active peerings..." because this is not always the case.
We might add at the end of the error message something like:
- To disable active peering launch liqoctl X
- To unoffload a namespace launch liqoctl Y

Actually, the ideal solution would be changing the returned error message to suggest a solution for each of the returned error, but since this is a shared function, I wouldn't suggest to use `liqoctl` when the user is not actually using it. So we should add a logic to understand when we are using liqoctl and print the suggestion. However, I'm not sure if it is worth it.
What do you guys think? @aleoli @fra98 @cheina97 

Maybe in future, it would be nice having a flag like `--force` that automatically removes everything that prevents Liqo from being uninstalled.

Comment (frisso) [reply pkg/liqoctl/uninstall/handler.go:70]: Is there any command we can suggest to look for active resources? (e.g., some "status"?)
In this case, the message could be "cannot uninstall because there are still some active resources. Check the status of your setup with command XXX and clean them properly to uninstall, or use the "--force" flag.

Comment (claudiolor) [reply pkg/liqoctl/uninstall/handler.go]: We finally decided to proceed with the best solution for the user: for each of the problems that prevent Liqo from being uninstalled we suggest the resolution

File: pkg/liqoctl/uninstall/handler.go (hunk 1 above)
Comment (claudiolor) [reply pkg/liqoctl/uninstall/handler.go]: Fixed
