### PR TITLE
bugfix pod termination

### LINKED ISSUE #598: Pods hang in terminating status
**Describe the bug**

When a pod is deleted in the local cluster (manually, or through a scale operations), it triggers the transition into terminating status and the removal of the remote replicaset. Although the remote replicaset is correctly deleted, and the finalizer of the local pod is removed, it nonetheless continues hanging in the terminating status, until the termination grace period expires.

**To Reproduce**
1. Establish a liqo peering with a remote cluster
2. Create a pod, forcing the scheduling in the remote cluster (optionally, increase the termination grace period to better observe the behavior) 
3. Delete the pod
4. Observe it remains in terminating status until the termination grace period expires.

**Expected behavior**
The pod should be correctly deleted when the remote replicaset removal succeeded

### PR DESCRIPTION
**Pull request by filippoprojetto**
# Description

Pod deletion initiated from the home pod was not completed correctly.
Indeed, the pod's container statuses in the home was never set to
terminated so the virtual kubelet was not able to delete pod.

This fix updates the container statuses in one go, when the foreign pod
is deleted, ie. we miss to update the home pod when the foreign
containers are terminated. Fixing this problem is out of scope and would
probably require modifying the pod black listing mechanism which seems
too risky at this time. Issue described here:
#721.

Resolves: #598

# How Has This Been Tested?

- Manually on my development workstation using 2 local clusters (created with kind).
- Unit tests added for PodIncomingReflector.

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]

File: pkg/virtualKubelet/apiReflection/reflectors/incoming/pods.go [hunk 1]
```diff
@@ -210,3 +210,27 @@ func (r *PodsIncomingReflector) isAllowed(ctx context.Context, obj interface{})
 	}
 	return !ok
 }
+
+// GetHomePod retrieves the shadow home pod given the foreign pod.
+var GetHomePod = func(pir *PodsIncomingReflector, foreignPod *corev1.Pod) (interface{}, error) {
```
Comment (giorio94) [inline pkg/virtualKubelet/apiReflection/reflectors/incoming/pods.go:215]: I feel this a bit weird as it is defined as a variable, instead of a proper function with the reflector as a receiver.
Still, I understand you need this for mocking during tests, so it seems fine to me.

File: pkg/virtualKubelet/apiReflection/reflectors/incoming/pods_test.go [hunk 2]
```diff
@@ -1,12 +1,18 @@
...
+	"flag"
+	"fmt"
+
 	. "github.com/onsi/ginkgo"
 	. "github.com/onsi/ginkgo/extensions/table"
 	. "github.com/onsi/gomega"
 	"github.com/onsi/gomega/types"
 	corev1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/klog"
```
Comment (giorio94) [inline pkg/virtualKubelet/apiReflection/reflectors/incoming/pods_test.go:15]:
```suggestion
	"k8s.io/klog/v2"
```

Unfortunately we never managed to make this a linter constraint

**Review by giorio94 — APPROVED** [review]

File: pkg/virtualKubelet/apiReflection/reflectors/incoming/pods.go (hunk 1 above)
Comment (filippoprojetto) [reply pkg/virtualKubelet/apiReflection/reflectors/incoming/pods.go]: I have tried a different implementation that allows mocking the function. It might be prettier.

Comment (giorio94) [reply pkg/virtualKubelet/apiReflection/reflectors/incoming/pods.go]: Looks great!

**Review by giorio94 — APPROVED** [review]

**Review by palexster — APPROVED** [review]
