### PR TITLE
controller: fix resource update bug

### LINKED ISSUE #1052: Only 1 node with GPU resource is showed on virtual node, other nodes' GPU are not
#### What happened:

I have 2 clusters peered by Liqo. On remote cluster, I added 4 nodes, each has 1 GPU, 
All total CPU, RAM, #POD on virtual node of local cluster are summed correctly. However, total GPU is not as the image showed below, total GPU is only 1.

```
export KUBECONFIG=~/.kube/config-liqo-eks-test-2
kubectl get node
NAME                                                STATUS   ROLES    AGE     VERSION
ip-192-168-44-202.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-60-162.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-70-120.ap-southeast-1.compute.internal   Ready    <none>   14d     v1.19.15-eks-9c63c4
ip-192-168-72-240.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-84-190.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU

export KUBECONFIG=~/.kube/config-liqo-eks-test-3
kubectl get node                                
NAME                                                STATUS   ROLES    AGE    VERSION
ip-192-168-79-162.ap-southeast-1.compute.internal   Ready    <none>   6d3h   v1.19.15-eks-9c63c4
liqo-c35ea397-925d-4e96-9b21-4c41f2539042           Ready    agent    3m8s   v1.19.13-eks-8df270

kubectl describe node liqo-c35ea397-925d-4e96-9b21-4c41f2539042
...
Capacity:
  attachable-volumes-aws-ebs:  156
  cpu:                         31330m
  ephemeral-storage:           188933193728
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      252697M
  nvidia.com/gpu:              1
  pods:                        232
Allocatable:
  attachable-volumes-aws-ebs:  156
  cpu:                         31330m
  ephemeral-storage:           188933193728
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      252697M
  nvidia.com/gpu:              1
  pods:                        232
...
```

#### What you expected to happen:
Total GPU on virtual node of local cluster must be a sum of all nodes on remote cluster.

#### How to reproduce it (as minimally and precisely as possible):

* Create 2 cluster
* Peer them with Liqo
* Add multiple GPU node to remote cluster

#### Anything else we need to know?:

I tried this on EKS-EKS and EKS-KubeADM (on-prem). Both have same issue

#### Environment:
- Liqo version: v0.3.2-beta.2
- Kubernetes version (use kubectl version): v1.21.0
- Cloud provider or hardware configuration: 2 EKS clusters, 1 EKS - KubeADM (on-prem)
- Network plugin and version:
- Install tools: liqoctl

### PR DESCRIPTION
**Pull request by CapacitorSet**
# Description

Fixes an error in the resource update algorithm - previously, when receiving a new resource type on a node it would overwrite the cluster resources rather than adding the new resources.

Fixes #1052

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Manual tests
- [x] Unit tests

### CODE REVIEW

File: pkg/liqo-controller-manager/resource-request-controller/resourceRequest_operator_test.go [hunk 1]
```diff
@@ -388,6 +388,48 @@ var _ = Describe("ResourceRequest Operator", func() {
...
+					toCheck.Sub(podReq[resourceName])
+					ScaleResources(resourceName, &toCheck, DefaultScaleFactor)
+					if quantity.Cmp(toCheck) != 0 {
+						return false
+					}
+				}
+				return true
+			}, timeout, interval).Should(BeTrue())
+
+			// Reproduces #1052.
```
Comment (aleoli) [inline pkg/liqo-controller-manager/resource-request-controller/resourceRequest_operator_test.go:412]:
```suggestion
			// Reproduces issue #1052.
```

**Review by aleoli — APPROVED** [review]
