### PR TITLE
Fix broadcaster & update adv operator

### LINKED ISSUE #217: virtual-kubelet is stuck in Init
**Describe the bug**
Once created two k3s clusters from scratch  and installed in both liqo, the "liqo-<...>" pod in the second cluster (in order of liqo installation) is stuck on the "Init:0/1" status.

**To Reproduce**
1. Install k3s and liqo in the first cluster and wait for all the pod to be up and running; 
2. Install k3s and liqo in the second cluster;
3. Run the `kubectl describe pod -n liqo liqo-<...>` in the second cluster;
4. See the following output:

```
Name:           liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-68f74654dc-gt52d
Namespace:      liqo
Priority:       0
Node:           rar-k3s-01/10.0.2.4
Start Time:     Tue, 01 Sep 2020 17:40:22 +0200
Labels:         app=virtual-kubelet
                cluster=8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
                pod-template-hash=68f74654dc
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-68f74654dc
Init Containers:
  crt-generator:
    Container ID:  
    Image:         liqo/init-vkubelet:latest
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/local/kubelet-setup.sh
    Args:
      /etc/virtual-kubelet/certs
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      POD_IP:     (v1:status.podIP)
      POD_NAME:  liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-68f74654dc-gt52d (v1:metadata.name)
    Mounts:
      /etc/virtual-kubelet/certs from virtual-kubelet-crt (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq (ro)
Containers:
  virtual-kubelet:
    Container ID:  
    Image:         liqo/virtual-kubelet:latest
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virtual-kubelet
    Args:
      --cluster-id
      8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
      --provider
      kubernetes
      --nodename
      liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
      --kubelet-namespace
      liqo
      --provider-config
      /app/kubeconfig/remote
      --home-cluster-id
      d9df783b-cd9b-4d25-ae37-231e21dc9739
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      APISERVER_CERT_LOCATION:  /etc/virtual-kubelet/certs/server.crt
      APISERVER_KEY_LOCATION:   /etc/virtual-kubelet/certs/server-key.pem
      VKUBELET_POD_IP:           (v1:status.podIP)
      VKUBELET_TAINT_KEY:       virtual-node.liqo.io/not-allowed
      VKUBELET_TAINT_VALUE:     true
      VKUBELET_TAINT_EFFECT:    NoExecute
    Mounts:
      /app/kubeconfig/remote from remote-kubeconfig (rw,path="kubeconfig")
      /etc/virtual-kubelet/certs from virtual-kubelet-crt (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  remote-kubeconfig:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vk-kubeconfig-secret-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
    Optional:    false
  virtual-kubelet-crt:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                   From                 Message
  ----     ------       ----                  ----                 -------
  Normal   Scheduled    <unknown>             default-scheduler    Successfully assigned liqo/liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-68f74654dc-gt52d to rar-k3s-01
  Warning  FailedMount  37m                   kubelet, rar-k3s-01  Unable to attach or mount volumes: unmounted volumes=[remote-kubeconfig], unattached volumes=[liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq remote-kubeconfig virtual-kubelet-crt]: timed out waiting for the condition
  Warning  FailedMount  35m (x10 over 39m)    kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "remote-kubeconfig" : secret "vk-kubeconfig-secret-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef" not found
  Warning  FailedMount  35m                   kubelet, rar-k3s-01  Unable to attach or mount volumes: unmounted volumes=[remote-kubeconfig], unattached volumes=[virtual-kubelet-crt liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq remote-kubeconfig]: timed out waiting for the condition
  Warning  FailedMount  34m (x2 over 34m)     kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "remote-kubeconfig" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  34m (x2 over 34m)     kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  34m (x4 over 34m)     kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "remote-kubeconfig" : secret "vk-kubeconfig-secret-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef" not found
  Warning  FailedMount  33m (x2 over 33m)     kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "remote-kubeconfig" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  33m (x2 over 33m)     kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  18m (x6 over 31m)     kubelet, rar-k3s-01  Unable to attach or mount volumes: unmounted volumes=[remote-kubeconfig], unattached volumes=[virtual-kubelet-crt liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq remote-kubeconfig]: timed out waiting for the condition
  Warning  FailedMount  13m (x3 over 25m)     kubelet, rar-k3s-01  Unable to attach or mount volumes: unmounted volumes=[remote-kubeconfig], unattached volumes=[remote-kubeconfig virtual-kubelet-crt liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq]: timed out waiting for the condition
  Warning  FailedMount  3m14s (x21 over 33m)  kubelet, rar-k3s-01  MountVolume.SetUp failed for volume "remote-kubeconfig" : secret "vk-kubeconfig-secret-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef" not found
```

Also, there is no liqo-<...> node in that cluster.

**Expected behavior**
The pod should be in "Running" status and there should be a liqo-<...> node in that cluster.

**Additional context**
`kubectl describe foreignclusters.discovery.liqo.io`
```
Name:         8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
Namespace:    
Labels:       cluster-id=8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
              discovery-type=LAN
Annotations:  <none>
API Version:  discovery.liqo.io/v1alpha1
Kind:         ForeignCluster
Metadata:
  Creation Timestamp:  2020-09-01T15:40:06Z
  Generation:          8
  Managed Fields:
    API Version:  discovery.liqo.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:outgoing:
          f:advertisement:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:uid:
    Manager:      advertisement-operator
    Operation:    Update
    Time:         2020-09-01T15:40:20Z
    API Version:  discovery.liqo.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:cluster-id:
          f:discovery-type:
      f:spec:
        .:
        f:allowUntrustedCA:
        f:apiUrl:
        f:clusterID:
        f:discoveryType:
        f:join:
        f:namespace:
      f:status:
        .:
        f:incoming:
          .:
          f:availableIdentity:
          f:identityRef:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
            f:uid:
          f:joined:
        f:outgoing:
          .:
          f:advertisementStatus:
          f:caDataRef:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
            f:uid:
          f:joined:
          f:remote-peering-request-name:
        f:ttl:
    Manager:      discovery
    Operation:    Update
    Time:         2020-09-01T15:40:49Z
    API Version:  discovery.liqo.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:incoming:
          f:peeringRequest:
            .:
            f:name:
            f:uid:
    Manager:         peering-request-operator
    Operation:       Update
    Time:            2020-09-01T15:40:49Z
  Resource Version:  1092
  Self Link:         /apis/discovery.liqo.io/v1alpha1/foreignclusters/8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
  UID:               e4ccbde0-f96a-4d80-bac8-776c87e49e02
Spec:
  Allow Untrusted CA:  true
  API URL:             https://10.0.2.5:6443
  Cluster ID:          8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
  Discovery Type:      LAN
  Join:                true
  Namespace:           liqo
Status:
  Incoming:
    Available Identity:  true
    Identity Ref:
      API Version:  v1
      Kind:         Secret
      Name:         pr-d9df783b-cd9b-4d25-ae37-231e21dc9739
      Namespace:    liqo
      UID:          9318644e-7ed4-49d9-a2bb-c1ccd50fe4c4
    Joined:         true
    Peering Request:
      Name:  8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
      UID:   dd249ebe-78cf-46b8-8c6f-8eb3810eea6f
  Outgoing:
    Advertisement:
      API Version:         sharing.liqo.io/v1alpha1
      Kind:                Advertisement
      Name:                advertisement-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef
      UID:                 7b5e6737-7b9a-4966-9052-970bdb8c996b
    Advertisement Status:  Deleting
    Ca Data Ref:
      API Version:                      v1
      Kind:                             Secret
      Name:                             8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-ca-data
      Namespace:                        liqo
      UID:                              08efcb08-9384-476c-9bb2-e5dd2dc1bdfd
    Joined:                             true
    Remote - Peering - Request - Name:  d9df783b-cd9b-4d25-ae37-231e21dc9739
  Ttl:                                  3
Events:                                 <none>
```

`kubectl get secrets -n liqo`
```
NAME                                                         TYPE                                  DATA   AGE
default-token-r5chc                                          kubernetes.io/service-account-token   3      52m
tunnelendpointcreator-operator-service-account-token-rszjk   kubernetes.io/service-account-token   3      52m
broadcaster-token-rkkx6                                      kubernetes.io/service-account-token   3      52m
peering-request-operator-token-qx4md                         kubernetes.io/service-account-token   3      52m
route-operator-service-account-token-t44br                   kubernetes.io/service-account-token   3      52m
sn-operator-token-4qknf                                      kubernetes.io/service-account-token   3      52m
tunnel-operator-service-account-token-ksr46                  kubernetes.io/service-account-token   3      52m
liqodash-admin-sa-token-lc7pv                                kubernetes.io/service-account-token   3      52m
discovery-sa-token-76r9c                                     kubernetes.io/service-account-token   3      52m
crdreplicator-operator-service-account-token-zbkkm           kubernetes.io/service-account-token   3      52m
podmutatoraccount-token-9l6z9                                kubernetes.io/service-account-token   3      52m
advertisement-operator-token-xk6fn                           kubernetes.io/service-account-token   3      52m
sh.helm.release.v1.liqo.v1                                   helm.sh/release.v1                    1      52m
ca-data                                                      Opaque                                1      51m
pr-d9df783b-cd9b-4d25-ae37-231e21dc9739                      Opaque                                1      51m
8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-ca-data                 Opaque                                1      51m
8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-8lbfs             kubernetes.io/service-account-token   3      51m
peering-request-webhook-certs                                Opaque                                2      51m
pod-mutator-secret                                           Opaque                                2      51m
liqo-8d40ca93-fd45-4b1d-af9c-f55cce5ed7ef-token-v4scq        kubernetes.io/service-account-token   3      51m
```

### PR DESCRIPTION
**Pull request by fraborg**
# Description
In this PR the broadcaster has been updated in order not to delete the secret for the virtualKubelet in the foreign cluster.
This fixes a race condition that in rare cases could happen: since the Advertisement can be created from 2 different threads, there are some cases in which one of them detects an error caused by the other one during the Advertisement creation; so the secret was deleted.
A check has also been added in the advertisement operator to assert the secret needed by the virtual-kubelet is present.

## Other changes
- added `NodeReference` in the adv status with the reference to the virtual node created by the virtual-kubelet; the node name is `liqo-<clusterID>`
- modified virtual-kubelet deployment name to `virtual-kubelet-<clusterID>`

Fixes #217

### CODE REVIEW

File: internal/advertisement-operator/controller.go [hunk 1]
```diff
@@ -250,7 +250,14 @@ func (r *AdvertisementReconciler) UpdateAdvertisement(adv *advtypes.Advertisemen
...
 func (r *AdvertisementReconciler) createVirtualKubelet(ctx context.Context, adv *advtypes.Advertisement) error {
 
-	name := "liqo-" + adv.Spec.ClusterId
+	secRef := adv.Spec.KubeConfigRef
+	_, err := r.AdvClient.Client().CoreV1().Secrets(secRef.Namespace).Get(context.Background(), secRef.Name, metav1.GetOptions{})
+	if errors.IsNotFound(err) {
+		klog.Errorf("Cannot find secret %v in namespace %v for the virtual kubelet; error: %v", secRef.Name, secRef.Namespace, err)
+		return err
+	}
+	name := "virtual-kubelet-" + adv.Spec.ClusterId
```
Comment (palexster) [inline internal/advertisement-operator/controller.go:259]: I would suggest to define those prefix should be defined as constants

**Review by palexster — APPROVED** [review]

**Review by alacuku — APPROVED** [review]
